sudo: required

services:
  - docker

language: java
dist: trusty

script:
  - mvn clean package -U
  - docker build -t jojo27/fifa-stats-tracker-users .

after_success:
  - docker login -u="$DOCKER_USERNAME2" -p="$DOCKER_PASSWORD2"
  - docker push jojo27/fifa-stats-tracker-users