kumuluzee:
  name: users-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
  discovery:
      etcd:
        hosts: http://127.0.0.1:2370

rest-config:
  string-property: Monday
  boolean-property: true
  integer-property: 23